CREATE TABLE `billboards` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `city_id` INT NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `type_id` INT NOT NULL,
  `format_id` INT NOT NULL,
  `light` TINYINT(1) NOT NULL,
  `side_num` INT NOT NULL,
  `surface_num_per_side` INT NOT NULL,
  `rent` DECIMAL(10,2) NOT NULL,
  `location` VARCHAR(255) NOT NULL,
  `owner_id` INT NOT NULL,
  `agent_id` INT NOT NULL,
  `comment` VARCHAR(512) DEFAULT NULL,
  `create_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`));